[repository]
name = "hypr-cube"
authors = ["dmitry"]
commit_pins = [
    ["efb50993780079460b0cbed1363e2166a2de1d9f", "b92f2cf36ee3a5e59a6c4533ef119837bd1cd09c"],
]

[hypr-cube]
description = "Compiz-style cube workspace switching"
output = "hypr-cube.so"
build = ["make all"]
